server:
  port: 8000

spring:
  application:
    name: douyin
  datasource:
    username: heiren
    password: eEderF8fPH6ACrek
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bt.vacant.zone:3306/heiren?useSSL=false
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  level:
    root: warn
    com.zk: trace
mybatis-plus:
      global-config:
        db-config:
          logic-delete-value: 1  #逻辑删除 1删除 0未删除
          logic-not-delete-value: 0
