server:
  port: 1000

spring:
  application:
    name: douyin
  datasource:
    username: heiren
    password: eEderF8fPH6ACrek
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bt.vacant.zone:3306/heiren?useSSL=false
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    host: 192.168.10.69
    port: 6380
    lettuce:
      pool:
        max-idle: 16 #redis连接池配置-最大保持闲置的连接数
        max-active: 20 #redis连接池配置-最大活跃的连接数
        max-wait: 1 #redis连接池配置-最大等待时间，单位毫秒
logging:
  level:
    root: warn
    com.zk: trace
mybatis-plus:
      global-config:
        db-config:
          logic-delete-value: 1  #逻辑删除 1删除 0未删除
          logic-not-delete-value: 0