server:
  port: 1000

spring:
  application:
    name: douyin
  datasource:
    username: heiren
    password: eEderF8fPH6ACrek
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bt.vacant.zone:3306/heiren?useSSL=false
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    host: 192.168.10.71
    port: 6380
    lettuce:
      pool:
        max-idle: 16 #redis连接池配置-最大保持闲置的连接数
        max-active: 20 #redis连接池配置-最大活跃的连接数
        max-wait: 1 #redis连接池配置-最大等待时间，单位毫秒
  rabbitmq:
    host: 192.168.10.71
    port: 5672
    username: guest
    password: guest
#    publisher-confirms: true   #开启发送确认(该写法过时了不适用)
    publisher-confirm-type: correlated #开启发送确认
    publisher-returns: true  #开启发送失败回退
    #开启ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #采取手动应答
        #concurrency: 1 # 指定最小的消费者数量
        #max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true # 是否支持重试
logging:
  level:
    root: warn
    com.zk: trace
mybatis-plus:
      global-config:
        db-config:
          logic-delete-value: 1  #逻辑删除 1删除 0未删除
          logic-not-delete-value: 0